### ISSUE TITLE
config.title, config.description not passed to translated pages

### ISSUE THREAD

**Issue by tkarkkainen** [Keats/gutenberg#1634]
# Bug Report

## Environment

Zola version: 0.14.1

## Expected Behavior
In the attached site, with `zola serve`, opening `http://127.0.0.1:1111/` should provide the following information:
```
lang: fi
section.title: Default language section
config.title: Default language title
config.description: Default language description
```

and `http://127.0.0.1:1111/en` should provide the following information:

```
lang: en
section.title: English section
config.title: Translated English title
config.description: Translated English description
```

[zola-debug-site.tar.gz](https://github.com/getzola/zola/files/7293617/zola-debug-site.tar.gz)

## Current Behavior

`http://127.0.0.1:1111/` works as expected, but `http://127.0.0.1:1111/en/`gives the following:

```
lang: en
section.title: English section
config.title: 
config.description: 
```

## Step to reproduce

See the attached zola site: [zola-debug-site.tar.gz](https://github.com/getzola/zola/files/7293617/zola-debug-site.tar.gz)

Or check the main files in the example below:

The template:
```html
<html>
<head></head>
<body>
	<pre>
		lang: {{ lang }}
		section.title: {{ section.title }}
		config.title: {{ config.title }}
		config.description: {{ config.description }}
	</pre>
</body>
```

config.toml:
```toml
# The URL the site will be built for
base_url = "https://example.com"

title = "Default language title"
description = "Default language description"
default_language="fi"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[languages.en]
generate_feed = true
build_search_index = true

[languages.en.translations]
title = "Translated English title"
description = "Translated English description"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here
```
