### ISSUE TITLE
When I use the `| safe` filter the template inheritance breaks

### ISSUE THREAD

**Issue by felipesere** [Keats/gutenberg#1801]
# Bug Report

## Environment

Zola version: `0.15.3`

## Expected Behavior
I can use `safe` to present the content that comes from markdown.

## Current Behavior
In one of my page templates ("blog-page.html") whenever I use  `{{ page.content | safe }}` the relationship to the parent template is lost.

For example

```html
# base.html
<html>
  <body>
    <main>
      This is in main!
      {% block content %}{% endblock %}
    </main>
  </body>
</html>


# blog-page.html
{% extends "base.html" %}

{% block content %}
<div class="blog stack-small">
  <div>
    <h1>{{ page.title }}</h1>
    <p class="text-gray-300">{{ page.date }}</p>
  </div>
    {{ page.content | safe }}
  </div>
</div>
{% endblock %}
```

As shown above, "This is main" won't be shown at all.
If I remove the `| safe` in  blog-page.html then the parent content shows just fine.

## Step to reproduce
Above example triggered the issue for me.

**Comment by Keats** [comment]
That's extremely weird, filters are considered at a completely time than inheritance...?

**Comment by felipesere** [comment]
Yeah, I thought so too!
These are the templates in question (with a bit more content):
[base.html](https://github.com/felipesere/amboseli/blob/refresh/templates/base.html)
[blog-page.html](https://github.com/felipesere/amboseli/blob/refresh/templates/blog-page.html)

and my config.toml is
```toml
# The URL the site will be built for
base_url = "https://felipesere.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
render_emoji = true
highlight_code = true
highlight_themes_css = [
  { theme = "base16-ocean-dark", filename = "css/syntax-theme-dark.css" },
  { theme = "base16-ocean-light", filename = "css/syntax-theme-light.css" },
]


[extra]
# Put all your custom variables here
```

and you can see it deployed as a branch preview here: https://deploy-preview-24--felipesere.netlify.app/blogs/elixir-pipeline-configuration/
