### ISSUE TITLE
No feed file generated in multilingual sites

### ISSUE THREAD

**Issue by theowenyoung** [Keats/gutenberg#1896]
# Bug Report

## Environment

Zola version: 0.15.3

## Expected Behavior

`en` as my second language, I configured the taxonomies `feed: true`, 

```toml
[languages.en]
taxonomies = [
  {name = "tags", feed = true, paginate_by = 20, lang = "en"},
  {name = "categories", feed = true, paginate_by = 20, lang = "en"},
]
```

When I build, there should be `public/en/categories/{name}/atom.xml` generated

## Current Behavior
There are no `public/en/categories/{name}/atom.xml` generated, they are only generated in default language, `public/categories/{name}/atom.xml`

## Step to reproduce

With this multilingual configure:

```toml
[languages.en]
taxonomies = [
  {name = "tags", feed = true, paginate_by = 20, lang = "en"},
  {name = "categories", feed = true, paginate_by = 20, lang = "en"},
]
```

**Comment by Keats** [comment]
I couldn't reproduce it in the `next` branch but I did find and fix a bug (https://github.com/getzola/zola/pull/1741/commits/4da81eb17e7995e09e6ede75d3e205a0c5f1cbd2) related to the position of the taxonomies feeds.

**Comment by theowenyoung** [comment]
Well, I made a minimal example repo for this issue: <https://github.com/theowenyoung/zola-reproduce-example>

```bash
git clone git@github.com:theowenyoung/zola-reproduce-example.git
zola build
```

You will see `public/categories/random/atom.xml`, but not for `public/zh/categories/random/atom.xml`.


[Issue track](https://github.com/getzola/zola/issues/1896)

Related config:

```toml
# The URL the site will be built for
base_url = "https://example.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false
generate_feed = true
taxonomies = [
  # You can enable/disable RSS
  {name = "categories", feed = true},
  {name = "tags", feed = true},
]
theme = "after-dark"
[languages.zh]
taxonomies = [
  # You can enable/disable RSS
  {name = "categories", feed = true},
  {name = "tags", feed = true},
]
[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here
```
