### ISSUE TITLE
linenos and hl_lines uses a table, need a class definition applied so I can style this differently

### ISSUE THREAD

**Issue by Jieiku** [Keats/gutenberg#1898]
I just found the linenos and hl_lines features, very cool. Was trying it out and noticed it uses an html table to do so.

The problem is that css meant for tables gets applied, which in some cases might be desired, or in other cases may not.

If a class were applied to this table eg: `<table class="code">` then people would have the option of excluding table styles from this block if that is what they wanted.

Here is what it currently looks like:

![2022-06-14_21-53-04](https://user-images.githubusercontent.com/106644/173742034-0fd25caa-046b-4156-891a-8fa8d045d59c.png)

If this table had a class I could exclude it like this: (the other table elements can easily be handled with inheritance)

```css
table:not(.code) {

}
```

Also need the mark tag used in code blocks to have a code class so I can do this too:

```css
mark:not(.code) {

}
```

# Update, then again this may not be necessary, I did not know about the `unset` keyword, I just override the regular css like this:

```scss
// Table Override, this is used for Zola linenos and hl_lines
code table {
  font-size: .8rem;
  th, tr, td {
    padding: .1rem;
  }
  // Highlighted text
  mark {
    background-color: var(--c2);
    color: unset;
  }
  tbody tr:nth-child(even), thead tr {
    background-color: unset;
  }
}
```

and now I have this:

![2022-06-14_23-22-38](https://user-images.githubusercontent.com/106644/173756736-4e478626-502e-4484-a768-1d47178cef46.png)

**Comment by Keats** [comment]
Why did you close it?
﻿

**Comment by Jieiku** [comment]
I resolved the issue by using the unset value in my css.

If you think it is still a good idea to add a class then feel free to reopen :)

here is what I am currently using now to override:

```
// Table Override, this is used for Zola's linenos and hl_lines
code table {
  font-size: .8rem;
  th, tr, td {
    padding: .1rem;
  }
  tbody tr td:last-child {
    width: 99%;
    min-width: 99%;
    max-width: 99%;
  }
  // Highlighted text
  mark {
    background-color: var(--c2);
    color: unset;
  }
  tbody tr:nth-child(even), thead tr {
    background-color: unset;
  }
}
```

which produces:

![2022-06-15_00-04-36](https://user-images.githubusercontent.com/106644/173763820-217a93d8-e702-48e1-aa53-9719832c0ceb.png)

I am very happy with this appearance.

**Comment by Jieiku** [comment]
I just pushed those css changes live, you can see them here:

https://abridge.netlify.app/overview-markdown-and-style/#code-blocks

**Comment by Jieiku** [comment]
After reviewing the docs I made a couple more adjustments, and I also fixed the code copy JavaScript function that I use so that it will not copy the line numbers:

```scss
// Table Override, this is used for Zola's linenos and hl_lines
code table {
  font-size: .8rem;
  td, th, tr {
    padding: 0;
    border-bottom: none;
  }
  tbody tr td:first-child {
    text-align: center;
    user-select: none;
  }
  tbody tr:nth-child(even), thead tr {
    background-color: unset;
  }
  // Highlighted text
  mark {
    display: block;
    background-color: var(--c2);
    color: unset;
    padding: 0;
  }
}
```

![2022-06-15_02-52-36](https://user-images.githubusercontent.com/106644/173803812-f8c76f98-11cb-4e45-9f71-e11489e485d5.png)

https://abridge.netlify.app/overview-markdown-and-style/#code-blocks

**Comment by Keats** [comment]
I think the difference between highlighted and non-highlighted is a bit too small no?

**Comment by Jieiku** [comment]
I completely agree, the difficulty is in making the difference more while still passing google lighthouse contrast requirements.

I just got this done:
![2022-06-15_14-43-44](https://user-images.githubusercontent.com/106644/173935054-c5528bdd-fa72-4ec1-8ff6-e28e8f28daa2.png)

For the dark theme I used the css brighten property:

```scss
// Mark Override, this is used for Zola's linenos and hl_lines
:root:not(.light) code table {
  mark {
    filter: brightness(120%);
    background-color: var(--c2);
  }
}
```

https://abridge.netlify.app/overview-markdown-and-style/#code-blocks
