### ISSUE TITLE
Add `ignored_static` similar to `ignore_content` but for the static folder

### ISSUE THREAD

**Issue by savchenko** [Keats/gutenberg#1925]
# Bug Report

## Environment

Zola version: v0.15.3

## Expected Behavior

```toml
ignored_content = ["*.icc", "readme.*", "README.*"]
```

Should exclude `foobar.icc` and `README.md`.

## Current Behavior
Both files are included in the `output_dir`.

## Step to reproduce

Running as following:
```toml
base_url = "https://foobar.com"
minify_html = false
output_dir = "_build"
compile_sass = false
build_search_index = false
ignored_content = ["*.icc", "readme.*", "Readme.*", "README.*"]

[slugify]
paths = "safe"
taxonomies = "safe"
anchors = "safe"

[markdown]
highlight_code = false
```

**P.S.** While we are at it, can `ignored_content` support regexp? Would allow much neater `?readme.*` and such.

**Comment by Keats** [comment]
I've tried with one one of the ignored_content testcase and it seems to work as expected, that's weird.


> P.S. While we are at it, can ignored_content support regexp? Would allow much neater ?readme.* and such.

`ignored_content` are globs so we support whatever https://docs.rs/globset/latest/globset/ is supported, not planning to add anything else.

**Comment by Keats** [comment]
Any updates?

**Comment by savchenko** [comment]
Re-tested with v0.16.1 on Win10 and Debian 11 running on WSL2.

File `./static/img/README.md` is copied to `./public/img/README.md` after `zola build`.

Config file:
```toml
base_url = "http://localhost/"
ignored_content = ["*.icc", "readme.*", "Readme.*", "README.*"]
compile_sass = false
build_search_index = false

[markdown]
highlight_code = false
```
