### ISSUE TITLE
[Question] How to deploy with Github Actions

### ISSUE THREAD

**Issue by little-method** [Keats/gutenberg#2054]
I want to deploy to another repository using Github Actions.(I referred to it [here](https://www.getzola.org/documentation/deployment/github-pages/#github-actions).)
However, the deploy fails.

Deploy Log
```
Starting deploy...
Fetching themes
Using zola 0.16.1
Building in my_site directory
Building with flags:
Building site...
Error: Failed to build the site
Error: Failed to load theme simple-dev-blog
Error: Reason: Failed to open file /github/workspace/my_site/themes/simple-dev-blog/theme.toml
Error: Reason: No such file or directory (os error 2)
```

.github/workflows/main.yml
```yaml
# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.0
        with:
          submodules: true
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.16.1
        env:
          # Target repository
          REPOSITORY: st-little/st-little.github.io
          # Target branch
          PAGES_BRANCH: gh-pages
          # Build directory
          BUILD_DIR: my_site
          # Provide personal access token
          TOKEN: ${{ secrets.TOKEN }}
          # Or if publishing to the same repo, use the automatic token
          #TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

.gitmodules
```
[submodule "my_site/themes/simple-dev-blog"]
	path = my_site/themes/simple-dev-blog
	url = https://github.com/bennetthardwick/simple-dev-blog-zola-starter.git
```

my_site/config.toml
```toml
# The URL the site will be built for
base_url = "https://st-little.github.io"

theme = "simple-dev-blog"
taxonomies = [ { name = "tags" } ]

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
icon = "icon.jpg"
profile_small = "icon.jpg"
footer_about = ""
nav = [
  { name = "Blog", path = "/blog/" }
]
```

The version of zola is 0.15.3.
Am I using Github Actions incorrectly?
