### ISSUE TITLE
`config.toml contains both default language specific information` warning incorrectly displays for any multilingual site

### ISSUE THREAD

**Issue by justint** [Keats/gutenberg#2137]
# Bug Report

## Environment

Zola version: zola 0.17.1

## Expected Behavior
```
Warning: config.toml contains both default language specific information at base and under section `[languages.en]`, which may cause merge conflicts. Please use only one to specify language specific information
```
This warning should only display whenever the condition it describes (`config.toml` containing both default language specific information at base and under another language section) is true.

## Current Behavior
This warning currently incorrectly displays any time a site is configured with a `[languages.XX]` section in the `config.toml`, even when neither the base section or language section has language specific information.

## Step to reproduce
1. Do a `zola init` in an empty directory, leave all options to their defaults.
2. In the `config.toml`, add empty `[languages]` and `[languages.en]` sections, and (optional) remove `build_search_index` key. You should have this left: 
   <details>
     <summary>config.toml</summary>

      ```toml
      # The URL the site will be built for
      base_url = "https://example.com"

      # Whether to automatically compile all Sass files in the sass directory
      compile_sass = true

      # Whether to build a search index to be used later on by a JavaScript library
      # build_search_index = false

      [markdown]
      # Whether to do syntax highlighting
      # Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
      highlight_code = false

      [languages]

      [languages.en]

      [extra]
      # Put all your custom variables here
      ```
   </details>

3. Run `zola serve`. Note the warning appears even though there's no language-specific information in either the base section or `en` language section.
