### ISSUE TITLE
 Search index for the second language indexes default language content.

### ISSUE THREAD

**Issue by EtoDemerzel0427** [Keats/gutenberg#2155]
# Bug Report

The following problem description is out-of-date. See the first reply.

## Environment

Zola version: Zola 0.17.1 (I also have tried 0.17.2)

## Expected Behavior
I removed the `build_search_index` in the base area, and added two `build_search_index` under the two languages part. Zola should be able to get the value and build the search index file. My configuration is as below:

```toml
default_language = "en"
# build_search_index = true
# generate_feed = true
# feed_filename = "atom.xml"
# feed_limit = 20

[languages]
    [languages.en]
        title = "My title"
        description = "desc."
        build_search_index = true
        generate_feed = true
        feed_filename = "atom.zh.xml"
        taxonomies = [
            { name = "tags", feed = true, paginate_by = 5  },
            { name = "categories", feed = true, paginate_by = 5 }
        ]
    [languages.zh]
        title = "我的标题"
        description = "描述"
        build_search_index = true
        generate_feed = true
        feed_filename = "atom.xml"
        taxonomies = [
            { name = "tags", feed = true, paginate_by = 5  },
            { name = "categories", feed = true, paginate_by = 5 }
        ]
```
The whole `config.toml` is available [here](https://github.com/EtoDemerzel0427/etodemerzel0427.github.io/blob/main/config.toml).

## Current Behavior

It seems Zola just fails to detect the `build_search_index` under the languages section. It does not build the index for both languages (the `elasticlunr.min.js` is not generated as well). 

## Step to reproduce
[Here](https://github.com/EtoDemerzel0427/etodemerzel0427.github.io) is my repository for this blog site. To enable Chinese indexing, you'll have to add `--features search/indexing-zh`.
