### ISSUE TITLE
Markdown-native code-block syntax for front-matter

### ISSUE THREAD

**Issue by eugenesvk** [Keats/gutenberg#2174]
Would be great if in instead of the `+++`/`---` you could optionally use markdown-native code blocks for the front-matter `toml`/`yaml`, this way you could get syntax highlighting and other editor integration like hitting your comment shortcut and getting the proper toml/yaml comment `#` instead of the html `<!-- -->`

```
+++
title = "+++ break syntax highlighting/commenting in an editor with Markdown support"
+++
```

```toml
title = "but backticks would solve that! you could use
```toml
key = 1
```"
description = "...or
```yaml
key = 1
```"
```

and then you get syntax highlighting and other goodies
```toml
title = "title"
```
```yaml
title : title
```
