### ISSUE TITLE
i18n sitemap taxonomies not working properly.

### ISSUE THREAD

**Issue by mehmetcansahin** [Keats/gutenberg#2183]
# Bug Report
i18n sitemap taxonomies not working properly.

## Environment

Zola version: 0.17.2

## Expected Behavior

Taxonomies must be added to the sitemap separately for each language.

## Current Behavior
Example: https://mehmetcansahin.com/sitemap.xml

```xml
<url>
<loc>https://mehmetcansahin.com/tags/xml/</loc> -->False, Correct: https://mehmetcansahin.com/tr/tags/xml/
</url>
<url>
<loc>https://mehmetcansahin.com/tags/zola/</loc> --> Default lang correct
</url>
```

## Step to reproduce
Create content in different languages and enter taxonomies in them.

**Comment by Keats** [comment]
Can you paste your config.toml as well?

**Comment by mehmetcansahin** [comment]
Of course, here it is:
```toml
title = "Mehmetcan Şahin"
description = "Personal Web Page"
base_url = "https://mehmetcansahin.com"
compile_sass = true
minify_html = true
build_search_index = true
generate_feed = true
taxonomies = [{ name = "tags", feed = true, lang = "en" }]
author = "Mehmetcan Şahin"
default_language = "en"

[languages.tr]
title = "Mehmetcan Şahin"
description = "Kişisel Web Sayfası"
generate_feed = true
build_search_index = true
taxonomies = [{ name = "tags", feed = true, lang = "tr" }]

[markdown]
highlight_code = true
highlight_theme = "ayu-mirage"

[extra]
show_word_count = true
show_reading_time = true
```
