### ISSUE TITLE
Zola not working on `aarch64` linux

### ISSUE THREAD

**Issue by rikhuijzer** [Keats/gutenberg#2332]
I'm using
```yaml
      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.17.2
```
on an Ampere Altra and it fails because there are no suitable binaries available.

Could the number of architectures be expanded in the releases?

And yes I know that architectures are a pain to build for. As a minimal solution, maybe https://buildjet.com is an option? I've used it for a while and they've got cheap runners and are easy to get working. Otherwise, QEMU might work too.
