### ISSUE TITLE
Feature request: build a non distroless docker image

### ISSUE THREAD

**Issue by ogarcia** [Keats/gutenberg#2361]
Having a distroless image is interesting for people who simply want to run zola directly, but if you want to use zola on a CI/CD system you need the image to contain a shell.

I think you could make two variants of the image, by default a distroless one and then another one based on Debian (to give an example).

You would have to modify the Dockerfile to make the from a variable:

<details>
<summary>Dockerfile</summary>

```Dockerfile
ARG DISTRO=gcr.io/distroless/cc

FROM rust:slim AS builder

RUN apt-get update -y && \
  apt-get install -y make g++ libssl-dev && \
  rustup target add x86_64-unknown-linux-gnu

WORKDIR /app
COPY . .

RUN cargo build --release --target x86_64-unknown-linux-gnu


FROM ${DISTRO}
COPY --from=builder /app/target/x86_64-unknown-linux-gnu/release/zola /bin/zola
ENTRYPOINT [ "/bin/zola" ]
```

</details>

And add these two additional steps in the CI:

<details>
<summary>CI steps</summary>

```yaml
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: latest=false
          tags: |
            type=ref,enable=true,priority=600,prefix=debian-,suffix=,event=tag

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          build-args: |
            DISTRO=debian:stable
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

</details>
