### ISSUE TITLE
Non-default language search index doesn't respect `[search]` config

### ISSUE THREAD

**Issue by welpo** [Keats/gutenberg#2405]
# Bug Report

## Environment

Zola version: 0.18.0

## Expected Behavior

With `config.toml`:

```toml
base_url = "https://example.com"
build_search_index = true

[search]
include_title = true
include_description = false
include_path = false
include_content = false

[languages.es]
build_search_index = true
```

I expected all search indexes (default language or not) to follow the `[search]` section config.

## Current Behavior

English (default) language respects the settings; non-default (Spanish in the example) does not. The non-default languages are generated with the default (all `true`) config.

![index size comparison](https://github.com/getzola/zola/assets/6399341/37dca085-4c3a-4a21-9a00-64c877acfb68)

This happens with both the json and javascript index format.

## Step to reproduce

See `config.toml` above and examine the search index of each language.

**Comment by welpo** [comment]
Exploring the code I realised the search settings must be set in each language as well, like this:

```toml
[languages.es]
build_search_index = true

[languages.es.search]
include_title = true
include_description = false
include_path = false
include_content = false
```
