### ISSUE TITLE
Sintax highlighting of `?Sized` rust code is invalid

### ISSUE THREAD

**Issue by sgued** [Keats/gutenberg#2416]
# Bug Report

## Environment

Zola version: 18.0

## Expected Behavior

In a rust code block, in a template, `?Sized` is valid and should be highlighted correctly.

![image](https://github.com/getzola/zola/assets/51865119/a1a67f10-284e-4164-b9d4-3c84c6260e22)

## Current Behavior

![image](https://github.com/getzola/zola/assets/51865119/b57b8ec0-da61-4e03-8517-ab1d95e837cc)

## Step to reproduce

Build a site with syntax highlighting enable, and include the following valid rust code block:

```rust
pub struct Testing<T: ?Sized> {
    testing: T,
}
```

# Workaround

This workaround fully disables highlighting of "invalid" code, so it may not be suitable for everyone.
Use `css` styles and add the following CSS, loaded after the syntax theme itself:

```css
// Fix bad syntax highlighting of ?Sized
.z-invalid {
  color: inherit;
  background-color: inherit;
}

.z-illegal {
  color: inherit;
  background-color: inherit;
}
```
