### ISSUE TITLE
How create a frontmatter extra object

### ISSUE THREAD

**Issue by vtmx** [Keats/gutenberg#2583]
Hello everyone, recently I needed to create an extra custom field where I would need to use objects. I tried the following ways and didn't succeed.

```yaml
extra:
 app:
   - name: nvim
     version: '2.0'
```

And:
```toml
[extra]
[extra.app]
name = 'nvim'
version = '2.0'
```

**Comment by vtmx** [comment]
I discovered:
```yml
extra:
  apps:
  - {
    name: nvim
    version: '2.0'
  }
```

Render:
```jinja2
{% if page.extra.apps %}
  {% for app in page.extra.apps %}
    {{ app.name }} - {{ app.version }}
  {% endfor %}
{% endif %}
  ```
