### ISSUE TITLE
`languages.en.build_search_index = true` doesn't work if `build_search_index` is false for the default language

### ISSUE THREAD

**Issue by salif** [Keats/gutenberg#2689]
# Bug Report

## Environment

Zola version: 0.19.2

## Expected Behavior

I want to enable search only for english language because default language Bulgarian `bg` is not supported.

## Current Behavior

Neither `search_index.en.js` nor `elasticlunr.min.js` file is generated.

## Step to reproduce

This is in my config.toml file:

```toml
default_language = "bg"
build_search_index = false

[languages.en]
build_search_index = true
```
